image: cirrusci/flutter

stages:
  - build

flutter_build_android:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build apk --target-platform android-arm64
    - mv build/app/outputs/apk/release/app-release.apk ./notes.apk
  artifacts:
    paths:
      - notes.apk

linux_build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends cmake ninja-build clang build-essential pkg-config libgtk-3-dev liblzma-dev lcov libvlc-dev vlc libsecret-1-dev libjsoncpp-dev
    - flutter config --enable-linux-desktop
    - flutter packages get
    - flutter build linux
  artifacts:
    paths:
      - build/linux/x64/release/bundle/*


flutter_lint:
  stage: build
  script:
    - flutter format . --output none --set-exit-if-changed

flutter_analyze:
  stage: build
  script:
    - flutter analyze ./lib
